name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  lint-docs:
    name: Lint docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7.0.1

      - name: Lint docs
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: .markdownlint.yaml
          fix: false
          globs: '**/*.md'

  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Lint (Ruff)
        run: python3 -m ruff check .

      - name: Type check (Mypy)
        run: python3 -m mypy custom_components tests

      - name: Format
        run: python3 -m ruff format . --check

      - name: Check JSON formatting (jq)
        run: |
          find . -name "*.json" -not -path "*/\.*" | while read -r file; do
            jq . "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done
          if [[ -n $(git status --porcelain) ]]; then
            echo "JSON files are not formatted correctly. Please run scripts/lint."
            git diff
            exit 1
          fi
