name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  pytest:
    name: "Pytest"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements_test.txt

      - name: Run tests with coverage
        run: |
          python3 -m pytest tests/ --cov=custom_components.resume_state --cov-report=term-missing | tee coverage_report.txt

      - name: Add Coverage Report to Summary
        run: |
          echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat coverage_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
